name: minio-on-github-actions
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: us-east-1
      AWS_EC2_METADATA_DISABLED: true
    services:
      minio:
        image: wktk/minio-server
        ports:
          - 9000:9000
        env:
          MINIO_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY_ID }}
          MINIO_SECRET_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
      - name: Add 127.0.0.1 minio to /etc/hosts
        run: echo "127.0.0.1 minio" | sudo tee -a /etc/hosts
      - uses: chrislennon/action-aws-cli@v1.1
      - name: make bucket
        run: aws --endpoint-url http://minio:9000/ s3 mb s3://sample-bucket
      - name: put object
        run: echo "sample-key" | aws --endpoint-url http://minio:9000/ s3 cp - s3://sample-bucket/sample/key
      - name: list objects
        run: aws --endpoint-url http://minio:9000/ s3 ls s3://sample-bucket/ --recursive
      - uses: chrislennon/action-aws-cli@v1.1
      - run: aws s3 ls
